[package]
name = "parallel-parser"
version = "0.1.0"
authors = ["John Keiser <john@johnkeiser.com>"]
edition = "2018"

[dependencies]
packed_simd = "*"
num = "*"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
